print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Jordan/Pictures/Artwork/3D/Unity/CAVE/CAVEProject/Assets/Models/Levels/WallLight.ma"`)
{		
	file -o "/Users/Jordan/Pictures/Artwork/3D/Unity/CAVE/CAVEProject/Assets/Models/Levels/WallLight.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Jordan/Pictures/Artwork/3D/Unity/CAVE/CAVEProject/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Jordan/Pictures/Artwork/3D/Unity/CAVE/CAVEProject/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Jordan/Pictures/Artwork/3D/Unity/CAVE/CAVEProject/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
